# Generated by Django 2.0.2 on 2018-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BirdID', models.CharField(max_length=30, null=True)),
                ('Location', models.CharField(max_length=30, null=True)),
                ('Age', models.CharField(max_length=30)),
                ('Parent', models.CharField(max_length=30)),
                ('Procedure', models.CharField(max_length=30)),
                ('Experimenter', models.CharField(max_length=30)),
                ('Alive', models.DateTimeField(auto_now_add=True)),
                ('Record_Last_Modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
