# Generated by Django 2.0.2 on 2018-03-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Finch',
            new_name='Finches',
        ),
    ]
