# Generated by Django 2.0.2 on 2018-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0003_auto_20180314_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='id',
        ),
        migrations.AlterField(
            model_name='finch',
            name='BirdID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
