# Generated by Django 2.0.2 on 2018-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0004_auto_20180315_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finch',
            name='Alive',
        ),
        migrations.AlterField(
            model_name='finch',
            name='Record_Last_Modified',
            field=models.DateField(auto_now=True),
        ),
    ]
