# Generated by Django 2.0.2 on 2018-04-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0007_auto_20180330_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='Experimenter',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
