# Generated by Django 2.0.2 on 2018-04-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0008_auto_20180404_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='Spectograms',
            field=models.FileField(blank=True, null=True, upload_to='spectrograms/%m/%D/%Y/'),
        ),
        migrations.AlterField(
            model_name='finch',
            name='Experimenter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
