# Generated by Django 2.0.2 on 2018-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0009_auto_20180421_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='Notes',
            field=models.TextField(help_text='Add notes here'),
        ),
        migrations.AlterField(
            model_name='finch',
            name='Spectograms',
            field=models.FileField(blank=True, default='No specs', upload_to=''),
        ),
    ]
