# Generated by Django 2.0.2 on 2018-05-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birds', '0011_auto_20180422_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='Alive',
            field=models.DateTimeField(),
        ),
    ]
