# Generated by Django 2.0.2 on 2018-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_item',
            name='Item_brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
